### ISSUE TITLE
Internal "namespace" for front matter?

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#238]
There will likely be an increasing number of configuration options that get done within front matter, and the question then becomes how to define those without conflicting with real data?

For example, we recently added `template_engine` for choosing between Liquid, ERB, etc. But what if you wanted to have an actual piece of content labeled `template_engine`? In the future we'll probably have `dependencies` so content can specify other content it's dependent on for rendering…also maybe a JavaScript block for instantiating web components used in a document…and so on and so forth.

So the question is, should we relocate all configuration to key off a single top-level term? Like `config` or `settings` or even `bridgetown`? So it would look something like:

```yaml
title: I'm a page!
order: 4
config:
  template_engine: haml
  dependencies:
  - tps_reports
  script: |
    import Report from "reporting_tools"
```

Or am I overthinking matters? (Been known to happen…)
