### ISSUE TITLE
feat: Cyclical relationship within a collection

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#392]
I haven't specifically proved this, but I believe we have a gap in our current relations logic: what if I want a collection to "belongs_to" and also "has_many" itself? This would be useful in documentation where Page A could reference Page B and C and pages B and C could know about the back-reference from Page A.

Probably need to add a "belongs_to_with_references" or something to that nature. (It _could_ be "has_and_belongs_to_many" but that sounds too much like a difference concept within Rails DB associations.)

I thought of this because I want to add "See Also" sections within our own documentation, and this feature would be the perfect fit. ☺️

**Comment by jaredcwhite** [comment]
An alternative approach could be that a collection's `has_many` to itself could be named in another way. We'd have to support alternative schema in the config though:

```yaml
collections:
  articles:
    output: true
    relations:
      belongs_to: articles
      has_many:
        key: article_backreferences
        collection: articles
      
```
