### ISSUE TITLE
Simplify front matter defaults syntax

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#50]
**Update:** we ended up opting for a "data cascade" folder-based approach rather than changing the syntax of the defaults key in the config. See #139 

----

I've always found the YAML syntax for defining front matter defaults to be extremely obtuse and I _always_ have to look up a reference to remember how the heck to write it out. Really all I want to do is:

```yaml
defaults:
  posts:
    layout: post
  pages:
    layout: page
  "some/path/to/stuff":
    category: stuff
```

Let's make this a whole lot better and then deprecate the old syntax with the goal of removing it for the 1.0 release.

Note: it should be a pretty straightforward swap because the old syntax is array-based, whereas the new one will be hash-based, so we can easily detect which syntax is being used.
