### ISSUE TITLE
Deep Merge of Frontmatter

### ISSUE THREAD

**Issue by rickychilcott** [bridgetownrb/bridgetown#695]
**Bridgetown Version**:
bridgetown 1.2.0.beta5 "Bonny Slope

**To Reproduce**
Create a resource with multiple levels of frontmatter:

```erb
---
example:
  from_resource: "from resource"
---
```

and also set config defaults:

```
defaults:
  - scope:
      path: "articles"
    values:
      layout: default
      example:
        from_config: "from config"
```

The defaults get totally clobbered and you don't get a value at `resource.data.example.from_config`

See example repo: https://github.com/rickychilcott/bridgetown-deep-merge-test

**Current behavior**
Last one wins

**Expected behavior**
Deep merge of front matter.

**Computing environment (please complete the following information):**
 - OS: Mac OS X
 - Browser: Brave
 - Browser Version: Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (arm64)
 - Ruby Version: 3.0.3p157

**Additional context**
I looked around the source to try to figure out where to write a failing test and ultimately a fix, but I couldn't find where to fix it. I did see the `Utils.deep_merge_hashes` utility class and it being used, but wasn't sure where to plug it in or the specs to modify to drive out the behavior.
