### ISSUE TITLE
Add support for symbolized hashes for frontmatter defaults in the Ruby initializer DSL

### ISSUE THREAD

**Issue by ayushn21** [bridgetownrb/bridgetown#704]
**Bridgetown Version**: 1.2

**Current behavior**

Frontmatter defaults can be specified in the `bridgetown.config.yml` as:

```yml
defaults:
  -
    scope: 
      path: "excluded_files/**/*"
    values: 
      sitemap: false 
```

To use this functionality in the Ruby DSL, only string keys can be used:

```ruby
config.defaults << {
  "scope" => { "path" => "excluded_files/**/*" },
  "values" => { "sitemap" => false }
}
```

**Expected behavior**

The ability to use symbolized keys would be more "Ruby":

```ruby
config.defaults << {
  scope: { path: "excluded_files/**/*" },
  values: { sitemap: false }
}
```
