### ISSUE TITLE
feat: merge multiple collections for a feed

### ISSUE THREAD

**Issue by whysthatso** [bridgetownrb/bridgetown#730]
## Summary

This feature adds an option to configure a resource collection that includes multiple other collections, kind of like a `timeline` concept. it can be used to easily create an overarching timeline page that includes multiple or all collections across the site's resources. 

## Motivation

I have a blog that includes two and more collections, currently the included `posts` and custom collections `links` and `status_updates`. while i need the to behave like independent collections for most of the site's structure, i would like my main index page to be a timeline of all of these resources merged in chronological order.

## Guide-level explanation

Meta-Collections

If you prefer to show multiple collections merged and ordered on a single page, you want to use a meta-collection.
These are configured principally like collections, but have an additional list of actually existing collections:

```yml
# bridgetown.config.yml

meta_collections:
  <name>:
    output: true
    permalink: pretty
    future: true
    includes:
      - coll_1
      - coll_2
 ```
The list of names needs to be identical, misspelled items will raise an error.

## Unresolved Questions

Some related issues might be:

https://github.com/bridgetownrb/bridgetown-feed/issues/10
https://github.com/bridgetownrb/bridgetown/issues/384
